name: Test example backend

on:
  push:
    branches:
      - main
    paths:
      - 'example-backend/**'
      - '.github/workflows/example-backend.yml'

defaults:
  run:
    working-directory: example-backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.8

    - name: Run testing
      run: go test ./...
